spring:
  application:
    name: demo-springboot
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

neu:
  classname: java
  count: 51
  person: {name: 张三, age: 30}

server:
  port: 9000
mybatis:
  mapper-locations:  classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
